package com.edpp.transaction.enums;

public enum TransactionStatus {
    PENDING, PROCESSING, COMPLETED, FAILED, REVERSED, DECLINED, 
    AUTHORIZED, CAPTURED, VOIDED, REFUNDED, PARTIALLY_CAPTURED,PARTIALLY_REFUNDED
}